const mongoose = require('mongoose');
require('dotenv').config();
const Service = require('./models/Service');

const appointmentServices = [
  { serviceId: '5029127764', serviceName: 'FIRST CONSULTATION (DR ASWINI RANA)', price: 800, priority: '1', serviceOwner: 'Dr Aswini Rana' },
  { serviceId: '5029396248', serviceName: 'ONLINE CONSULTATION (DR ASWINI RANA)', price: 800, priority: '1', serviceOwner: 'Dr Aswini Rana' },
  { serviceId: '5031163852', serviceName: 'INFLUVAC TETRA CLINIC', price: 0, priority: '1', serviceOwner: 'Dr Aswini Rana' },
  { serviceId: '5026293477', serviceName: 'FOLLOW UP CONSULTATION(DR. ASWINI RANA)', price: 800, priority: '2', serviceOwner: 'Dr Aswini Rana' },
  { serviceId: '5029142824', serviceName: 'REPORT', price: 0, priority: '2', serviceOwner: 'Dr Aswini Rana' },
  { serviceId: '5029218628', serviceName: 'MEDICAL CERTIFICATE', price: 800, priority: '2', serviceOwner: 'Dr Aswini Rana' },
  { serviceId: '5030174737', serviceName: 'CONSULTATION (DR AISHEE BHATTACHARYA)', price: 0, priority: '2', serviceOwner: '-' },
  { serviceId: '5030478139', serviceName: 'NEBULIZATION AT CLINIC', price: 0, priority: '2', serviceOwner: '-' },
  { serviceId: '5030478140', serviceName: 'NEBULIZATION AT HOME', price: 0, priority: '2', serviceOwner: '-' },
  { serviceId: '5030554897', serviceName: 'VARICELLA VACCINE', price: 0, priority: '2', serviceOwner: '-' },
  { serviceId: '5030554899', serviceName: 'TRESIVAC PFS VACCINE', price: 0, priority: '2', serviceOwner: '-' },
  { serviceId: '5030555214', serviceName: 'INFLUVAC TETRA HOME', price: 0, priority: '2', serviceOwner: '-' },
  { serviceId: '5030555216', serviceName: 'CONSULTATION(DR DEBABRATA MAITY)', price: 0, priority: '2', serviceOwner: '-' },
  { serviceId: '5030555217', serviceName: 'CONSULTATION (DR SUBRATA BISWAS)', price: 0, priority: '2', serviceOwner: '-' },
  { serviceId: '5030555218', serviceName: 'DRESSING', price: 0, priority: '2', serviceOwner: '-' },
  { serviceId: '5030555222', serviceName: 'PNEUMOVAX 23 CLINIC', price: 0, priority: '2', serviceOwner: '-' },
  { serviceId: '5030637487', serviceName: 'INFLUVAC TETRA CLINIC', price: 0, priority: '2', serviceOwner: '-' },
  { serviceId: '5030637489', serviceName: 'PNEUMOVAX 23 HOME', price: 0, priority: '2', serviceOwner: '-' },
  { serviceId: '5030637490', serviceName: 'ECG CLINIC', price: 0, priority: '2', serviceOwner: '-' },
  { serviceId: '5030637491', serviceName: 'ECG HOME', price: 0, priority: '2', serviceOwner: '-' },
  { serviceId: '5030642211', serviceName: 'DIETICIAN', price: 0, priority: '2', serviceOwner: '-' },
  { serviceId: '5030642212', serviceName: 'PREVNAR 20 HOME', price: 0, priority: '2', serviceOwner: '-' },
  { serviceId: '5030642213', serviceName: 'PREVNAR 20 CLINIC', price: 0, priority: '2', serviceOwner: '-' },
  { serviceId: '5030643554', serviceName: 'HOLTER HOME', price: 0, priority: '2', serviceOwner: '-' },
  { serviceId: '5030669613', serviceName: 'CONSULTAION( DR PRAVEEN KUMAR)', price: 0, priority: '2', serviceOwner: '-' },
  { serviceId: '5030955684', serviceName: 'DR SAURAV SARKAR', price: 1000, priority: '2', serviceOwner: '-' },
  { serviceId: '5030956103', serviceName: 'DR KRISHANKO DAS', price: 800, priority: '2', serviceOwner: '-' },
  { serviceId: '5031100361', serviceName: 'DR KARAN SEHGAL', price: 1200, priority: '2', serviceOwner: '-' },
  { serviceId: '5031216752', serviceName: 'DR DEBABRATA MAITY', price: 1200, priority: '2', serviceOwner: '-' },
  { serviceId: '5031224011', serviceName: 'Rabivax Vaccine', price: 200, priority: '2', serviceOwner: '-' }
].map(s => ({ ...s, type: 'Appointment', gst: 0, code: '' }));

const otherServices = [
  { serviceName: 'BP CHECKUP HOME', price: 100 },
  { serviceName: 'IM INJECTION HOME', price: 300 },
  { serviceName: 'IV CANNULA PROCEDURE CHARGE HOME', price: 1500 },
  { serviceName: 'IV INJECTION CHARGE HOME', price: 400 },
  { serviceName: 'BP CHECKUP CLINIC', price: 50 },
  { serviceName: 'IM INJECTION CLINIC', price: 200 },
  { serviceName: 'STITCH CUTTING UPTO 5', price: 300 },
  { serviceName: 'STITCH CUTTING >5', price: 500 },
  { serviceName: 'STITCHING UPTO 5', price: 500 },
  { serviceName: 'STITCHING >5', price: 1000 },
  { serviceName: 'VACCINATION PROCEDURE CHARGE (HOME)', price: 300 },
  { serviceName: 'VACCINATION PROCEDURE CHARGE (CLINIC)', price: 200 },
  { serviceName: 'CBG', price: 100 },
  { serviceName: 'PULMONARY FUNCTION TEST', price: 1000 },
  { serviceName: 'FOLEYS CATHETERISATION PROCEDURE CHARGE', price: 2000 },
  { serviceName: 'DRESSING CHARGE (SMALL)', price: 500 },
  { serviceName: 'IV CANNULA PROCEDURE CHARGE CLINIC', price: 1000 },
  { serviceName: 'IV INJECTION CHARGE CLINIC', price: 200 },
  { serviceName: 'SC INSULIN CLINIC', price: 100 },
  { serviceName: 'IM INJECTION RABIES CLINIC', price: 300 },
  { serviceName: 'EEG', price: 1800 },
  { serviceName: 'DOCTOR HOME VISIT CHARGE', price: 4000 },
  { serviceName: 'NURSE HOME VISIT CHARGE', price: 500 },
  { serviceName: 'ABPM', price: 2500 },
  { serviceName: 'KETO DIASTIX TEST', price: 200 },
  { serviceName: 'ECG HOME', price: 600 },
  { serviceName: 'TROPONIN I', price: 800 },
  { serviceName: 'REG FEE (DR ARANYAK SARKAR)', price: 200 },
  { serviceName: 'HOLTER', price: 3000 },
  { serviceName: 'REG FEE (DR AISHEE)', price: 200 },
  { serviceName: 'REG FEE (DR T. DHAR)', price: 200 },
  { serviceName: 'REG FEE(DR KOHENA ROY)', price: 100 },
  { serviceName: 'INJ SC', price: 100 },
  { serviceName: 'GLOFLEX STOP COCK', price: 130 },
  { serviceName: 'IV FLUID CHANGE CHARGE', price: 500 },
  { serviceName: 'SALINE STAND/DAY', price: 200 },
  { serviceName: 'NEBULIZATION CHARGE(HOME)', price: 300 },
  { serviceName: 'NCV STUDY IN BOTH UPPER LIMBS', price: 1800 },
  { serviceName: 'NCV STUDY IN BOTH LOWER LIMBS', price: 2000 },
  { serviceName: 'NCV ALL 4 LIMBS', price: 2800 },
  { serviceName: 'NCV STUDY IN FACIAL NERVE', price: 1500 },
  { serviceName: 'NCV STUDY IN BRACHIAL PLEXUS', price: 3500 },
  { serviceName: 'EMG & NCV STUDY IN BORTH UPPER LIMBS', price: 3600 },
  { serviceName: 'EMG & NCV STUDY IN BOTH LOWER LIMBS', price: 3600 },
  { serviceName: 'EMG & NCV STUDY IN ALL 4 LIMBS', price: 4500 },
  { serviceName: 'EMG STUDY IN BOTH UPPER LIMBS', price: 2400 },
  { serviceName: 'EMG STUDY IN BOTH LOWER LIMBS', price: 2400 },
  { serviceName: 'EMG STUDY IN ALL 4 LIMS', price: 4500 },
  { serviceName: 'VEP STUDY', price: 2000 },
  { serviceName: 'BERA STUDY', price: 2000 },
  { serviceName: 'RNST', price: 2500 },
  { serviceName: 'SSEP IN BOTH UPPER LIMBS', price: 2800 },
  { serviceName: 'SSEP IN BOTH LOWER LIMBS', price: 2800 },
  { serviceName: 'BLINK - REFLEX', price: 2000 },
  { serviceName: 'VIDEO EEG (3H)', price: 5000 },
  { serviceName: 'DRESSING CHARGE (LARGE)', price: 1000 },
  { serviceName: 'SC INSULIN HOME', price: 200 },
  { serviceName: 'HOME COLLECTION CHARGE (RATRI)', price: 0 },
  { serviceName: 'HOME COLLECTION CHARGE (MAHI)', price: 0 },
  { serviceName: 'IV CANNULA INJ CHARGE HOME', price: 500 },
  { serviceName: 'HOME SALINE', price: 500 },
  { serviceName: 'ECG CLINIC', price: 350 },
  { serviceName: 'FOLEY CATHETER REMOVAL CHARGE', price: 800 },
  { serviceName: 'STAND HOME', price: 200 },
  { serviceName: 'NEBULIZATION AT CLINIC', price: 200 },
  { serviceName: 'REG FEE(DR PRAVEEN)', price: 200 },
  { serviceName: 'ENEMA', price: 2000 },
  { serviceName: 'REG FEES DR KARAN', price: 200 },
  { serviceName: 'HOME DRESSING', price: 1000 },
  { serviceName: 'REG FEES DR RITWIK GHOSH HALDER', price: 200 },
  { serviceName: 'CBG HOME', price: 200 },
  { serviceName: 'SALINE CLINIC', price: 300 },
  { serviceName: 'HOLTER REMOVE CHARGE HOME', price: 200 },
  { serviceName: 'REG FEE(DR SUBRATA BISWAS)', price: 200 },
  { serviceName: 'DRESSING CHARGE LARGE', price: 1000 },
  { serviceName: 'REG FEE (DR NILANJAN CHANDRA)', price: 200 },
  { serviceName: 'REG FEE (DR KRISHANKO DAS)', price: 200 },
  { serviceName: 'REG FEES DR (SUBRATA BISWAS)', price: 200 },
  { serviceName: 'IRON INJECTION PROCEDURE HOME', price: 3000 },
  { serviceName: 'CANNULA REMOVE', price: 500 },
  { serviceName: 'HOME BLOOD COLLECTION KP', price: 0 },
  { serviceName: 'REG FEE(SAURAV SARKAR)', price: 200 },
  { serviceName: 'TROP T PROCEDURE CHARGE', price: 200 },
  { serviceName: 'NEBULIZATION AT HOME', price: 300 },
  { serviceName: 'NCV BOTH LOWER LIMBS', price: 1800 },
  { serviceName: 'PHYSIOTHERAPY/DAY', price: 400 },
  { serviceName: 'HOLTER MONITORING(48)', price: 4400 },
  { serviceName: 'HOLTER MONITORING(72HOURS)', price: 5170 },
  { serviceName: 'NCV HOMECHARGE', price: 200 },
  { serviceName: 'REG FEES (DR DEBABRATA MAITY)', price: 200 },
  { serviceName: 'SLEEP STUDY/POLYSOMNOGRAPHY', price: 6000 },
  { serviceName: 'IV CANNULA INJ CHARGE CLINIC', price: 500 }
].map(s => ({ ...s, type: 'Other', gst: 0, code: '', serviceOwner: '-' }));

mongoose.connect(process.env.MONGO_URI)
  .then(async () => {
    console.log('Connected. Clearing old services...');
    await Service.deleteMany({});
    console.log('Inserting seed data...');
    await Service.insertMany([...appointmentServices, ...otherServices]);
    console.log('Success!');
    process.exit(0);
  })
  .catch(err => {
    console.error(err);
    process.exit(1);
  });
